### ISSUE TITLE
show paper title and journal

### ISSUE THREAD

**Issue by bendichter** [jnjahncke/o-index#1]
<img width="1240" alt="image" src="https://github.com/jnjahncke/o-index/assets/844306/39c5d54c-501c-4824-8144-44689b359974">

The app works for me. Amazing!

One suggestion: It would be helpful for me if the table showed the title of the each paper and the journal where it was published.

**Comment by jnjahncke** [comment]
Woo hoo! Great o-index Ben! We have now updated the app (www.tinyurl.com/o-index/) to include paper name and journal.

**Comment by bendichter** [comment]
Looks great! Thanks!
